### ISSUE TITLE
Unresolved reference when use from kotlin

### ISSUE THREAD

**Issue by alxsemn** [mfvanek/pg-index-health-test-starter#2]
> Task :apps:service-registry-back:compileTestKotlin FAILED
e: /Users/asemenov/prj/tsac-sr/apps/service-registry-back/src/test/kotlin/ru/vtb/tsac/serviceregistry/DatabaseStructureHealthTest.kt: (3, 29): Unresolved reference: index
e: /Users/asemenov/prj/tsac-sr/apps/service-registry-back/src/test/kotlin/ru/vtb/tsac/serviceregistry/DatabaseStructureHealthTest.kt: (4, 29): Unresolved reference: table
e: /Users/asemenov/prj/tsac-sr/apps/service-registry-back/src/test/kotlin/ru/vtb/tsac/serviceregistry/DatabaseStructureHealthTest.kt: (22, 46): Unresolved reference: IndexesMaintenanceOnHost
e: /Users/asemenov/prj/tsac-sr/apps/service-registry-back/src/test/kotlin/ru/vtb/tsac/serviceregistry/DatabaseStructureHealthTest.kt: (25, 45): Unresolved reference: TablesMaintenanceOnHost

**Comment by mfvanek** [comment]
@alxsemn thank you very much for reporting this issue.
It's already fixed in release 0.3.1.1
https://repo1.maven.org/maven2/io/github/mfvanek/pg-index-health-test-starter/0.3.1.1/
